### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by monzerfoda** [judge2020/ez-MBAM-3#2]
The file 'C:\Users\mozerfoda\AppData\Local\Temp\activation218.exe' already exists. | Stacktrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)   at ez_MBAM.MainWindow.<button_Copy2_Click>d__9.MoveNext()

**Comment by judge2020** [comment]
Malwarebytes has already patched this method anyways (blocking the activation server via HOSTS file) so I'll go ahead and archive this.
